/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_chance_jni_JNIDemo */

#ifndef _Included_cc_chance_jni_JNIDemo
#define _Included_cc_chance_jni_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_chance_jni_JNIDemo
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_chance_jni_JNIDemo_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
